course/urls.py
from django.urls import path

app_name = 'course'

urlpatterns = [

]

course_management/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.urls import path, include
from person.views import DashboardView

urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), {'next_page': '/'}, name='logout'),
    path('persons/', include('person.urls', namespace='person')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

person/urls.py
from django.urls import path
from person.views import PersonListView, PersonCreateView, CeleryBulkStudentCreateView

app_name = 'person'

urlpatterns = [
    path('', PersonListView.as_view(), name='person_list'),
    path('create/', PersonCreateView.as_view(), name='create_person'),
    path('bulk_student_create/', CeleryBulkStudentCreateView.as_view(), name='bulk_student_create'),
]

person/models.py
from django.contrib.auth.models import User
from django.db import models

roll_choices = (
    (1, 'Student'),
    (2, 'Teacher'),
    (3, 'Admin')
)

gender_choices = (
    (1, 'Male'),
    (2, 'Female'),
    (3, 'Other'),
)

department_choices = (
    (1, 'N/A'),  # for admin
    (2, 'CSE'),
    (3, 'EEE'),
    (4, 'Civil'),
    (5, 'Architecture'),
    (6, 'DBA'),
    (7, 'Law'),
    (8, 'English'),
    (9, 'Pharmacy'),
)


class PersonQuerySet(models.QuerySet):
    def teachers(self):
        return self.filter(user_roll=2)

    def students(self):
        return self.filter(user_roll=1)


class PersonManager(models.Manager):
    def get_queryset(self):
        return PersonQuerySet(self.model, using=self._db)

    def teachers(self):
        return self.get_queryset().teachers()

    def students(self):
        return self.get_queryset().students()


class Person(models.Model):
    user = models.ForeignKey(User, related_name='person', on_delete=models.CASCADE)
    mobile = models.CharField(max_length=50, null=True, blank=True)
    identification_number = models.CharField(max_length=50, null=True, blank=True)
    department = models.PositiveSmallIntegerField(choices=department_choices, default=1)
    date_of_birth = models.DateField(null=True, blank=True)
    gender = models.PositiveSmallIntegerField(choices=gender_choices, default=1)
    user_roll = models.PositiveSmallIntegerField(choices=roll_choices, default=1)

    active = models.BooleanField(default=True)  # for soft delete

    # custom manager, as django treats the first manager as default manager,
    # we have to define the objects as the first manager to get the built-in functionality.
    objects = models.Manager()
    people = PersonManager()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.get_user_roll_display()) + ': ' + str(self.identification_number) \
               + ', username: ' + str(self.user.username)

    class Meta:
        db_table = 'persons'
        ordering = ('-created_at',)

person/forms.py
from django import forms
from person.models import Person
from django.core.validators import MinValueValidator, MaxValueValidator


class PersonForm(forms.ModelForm):
    email = forms.EmailField(required=True, widget=forms.EmailInput(
        attrs={'class': 'form-control form-group__input'}))
    password = forms.CharField(required=True, widget=forms.PasswordInput(
        attrs={'class': 'form-control form-group__input'}))
    first_name = forms.CharField(required=True, widget=forms.TextInput(
        attrs={'class': 'form-control form-group__input'}))
    last_name = forms.CharField(required=True, widget=forms.TextInput(
        attrs={'class': 'form-control form-group__input'}))

    class Meta:
        model = Person
        exclude = ('id', 'user', 'active', 'created_at', 'updated_at')
        widgets = {
            'mobile': forms.TextInput(
                attrs={'class': 'form-control form-group__input'}),
            'identification_number': forms.TextInput(
                attrs={'class': 'form-control form-group__input'}),
            'department': forms.Select(
                attrs={'class': 'form-control simple-select form-group__input'}),
            'date_of_birth': forms.TextInput(
                attrs={'class': 'form-control form-group__input daterange-input-single'}),
            'gender': forms.Select(
                attrs={'class': 'form-control simple-select form-group__input'}),
            'user_roll': forms.Select(
                attrs={'class': 'form-control simple-select form-group__input'}),
        }


class CreateRandomStudentForm(forms.Form):
    total = forms.IntegerField(validators=[MinValueValidator(50), MaxValueValidator(5000)])

person/views/dashboard.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import csrf_exempt
import logging

logger = logging.getLogger('course_management')


class DashboardView(View):
    @csrf_exempt
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        context = {

        }
        return render(request, 'dashboard.html', context)

person/views/person.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db import transaction
from django.db.models import Q
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import csrf_exempt
import logging
from django.conf import settings
from person.models import Person
from person.forms import PersonForm, CreateRandomStudentForm
from person.tasks import create_random_students

logger = logging.getLogger('course_management')


class PersonListView(View):
    @csrf_exempt
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        page = request.GET.get('page', settings.DEFAULT_PAGE)
        per_page = request.GET.get('per_page', settings.PER_PAGE)

        try:
            persons = Person.objects.filter(active=True)
            paginator = Paginator(persons, per_page)

            try:
                persons = paginator.page(page)
            except PageNotAnInteger:
                persons = paginator.page(1)
            except EmptyPage:
                persons = paginator.page(paginator.num_pages)

            context = {
                'persons': persons,
            }
            return render(request, 'person/list.html', context)

        except Exception as e:
            logger.error(str(e))
            messages.error(request, str(e))
            return redirect('dashboard')


class PersonCreateView(View):
    @csrf_exempt
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):

        try:
            form = PersonForm()
            context = {
                'form': form,
            }
            return render(request, 'person/create.html', context)

        except Exception as e:
            logger.error(str(e))
            messages.error(request, str(e))
            return redirect('dashboard')

    def post(self, request):

        try:
            form = PersonForm(request.POST or None)
            if form.is_valid():
                data = form.cleaned_data
                # create django User first
                first_name = data.get('first_name')
                last_name = data.get('last_name')
                email = data.get('email')
                password = data.get('password')
                user = User()
                user.username = email
                user.email = email
                user.set_password(password)
                user.first_name = first_name
                user.last_name = last_name
                user.save()  # user created
                # now create person
                mobile = data.get('mobile')
                identification_number = data.get('identification_number')
                department = data.get('department')
                date_of_birth = data.get('date_of_birth')
                gender = data.get('gender')
                user_roll = data.get('user_roll')
                person = Person()
                person.user = user
                person.mobile = mobile
                person.identification_number = identification_number
                person.department = department
                person.date_of_birth = date_of_birth
                person.gender = gender
                person.user_roll = user_roll
                person.save()

                messages.success(request, 'Successfully created User: {}'.format(person.user.username))
                return redirect('person:person_list')
            else:
                logger.error(str(form.errors))
                context = {
                    'form': form,
                }
                return render(request, 'person/create.html', context)

        except Exception as e:
            logger.error(str(e))
            messages.error(request, str(e))
            return redirect('dashboard')


class CeleryBulkStudentCreateView(View):
    @csrf_exempt
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        try:
            form = CreateRandomStudentForm()
            context = {
                'form': form,
            }
            return render(request, 'person/celery_bulk_create.html', context)

        except Exception as e:
            logger.error(str(e))
            messages.error(request, str(e))
            return redirect('dashboard')

    def post(self, request):
        try:
            # import pdb;pdb.set_trace()
            form = CreateRandomStudentForm(request.POST or None)
            if form.is_valid():
                total = form.cleaned_data.get('total')
                # run process in background, returns response(not full) immediately
                create_random_students.delay(total)
                # run process in foreground, returns response after completing the task
                # create_random_students(total)
                messages.success(request, 'Successfully created total {} students.'.format(total))
                return redirect('person:person_list')
        except Exception as e:
            logger.error(str(e))
            messages.error(request, str(e))
            return redirect('dashboard')

person/templates/person/celery_bulk_create.html
{% extends 'sidebar.html' %}
{% load static %}
{% load custom_tags %}

{% block main_content %}
    <div class="main-content-outer no-padding-top">
        <div class="main-content-inner">
            <section class="pdb50">
                <div class="container-fluid">
                    <div class="pdt10 clearfix">
                        <h2 class="page-title mb30">
                            Add Bulk Student
                        </h2>
                    </div>
                    <!-- start main table box -->
                    <div class="form-modal form-block">
                        <form method="post" action="{% url 'person:bulk_student_create' %}">
                            {% csrf_token %}
                            {% for field in form %}
                                    <div class="col-md-12">
                                        <div class="form-group{% if field.errors %} has-error{% endif %}">
                                            <label for="{{ field.id_for_label }}">{{ field.label }}: </label>
                                            <!-- {{ field.label }} -->
                                            {{ field }}
                                            {% for error in field.errors %}
                                                <p class="help-block">{{ error }}</p>
                                            {% endfor %}
                                        </div>
                                    </div>
                                {% endfor %}
                            <div class="action-footer mt15">
                                <button type="button" class="btn-reset" onclick="goBack()">
                                    Back
                                </button>
                                <button type="submit" class="btn base-bg">
                                    Save changes
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </section>
        </div>
    </div>
{% endblock %}

{% block javascript %}
    <script>
        function goBack() {
            window.history.back();
        }

    </script>
{% endblock %}

person/templates/person/create.html
{% extends 'sidebar.html' %}
{% load static %}
{% load custom_tags %}

{% block main_content %}
    <div class="main-content-outer no-padding-top">
        <div class="main-content-inner">
            <section class="pdb50">
                <div class="container-fluid">
                    <div class="pdt10 clearfix">
                        <h2 class="page-title mb30">
                            Add User
                        </h2>
                    </div>
                    <!-- start main table box -->
                    <div class="form-modal form-block">
                        <form method="post" action="{% url 'person:create_person' %}">
                            {% csrf_token %}
                            <div class="row">


                                {% for field in form %}
                                    <div class="col-md-12">
                                        <div class="form-group{% if field.errors %} has-error{% endif %}">
                                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                            <!-- {{ field.label }} -->
                                            {{ field }}
                                            {% for error in field.errors %}
                                                <p class="help-block">{{ error }}</p>
                                            {% endfor %}
                                        </div>
                                    </div>
                                {% endfor %}


                            </div>
                            <div class="action-footer mt15">
                                <button type="button" class="btn-reset" onclick="goBack()">
                                    Back
                                </button>
                                <button type="submit" class="btn base-bg">
                                    Save changes
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </section>
        </div>
    </div>
{% endblock %}

{% block javascript %}
    <script>
        function goBack() {
            window.history.back();
        }

    </script>
{% endblock %}

person/templates/person/list.html
{% extends 'sidebar.html' %}
{% load static %}
{% load custom_tags %}

{% block main_content %}
    <div class="main-content-outer no-padding-top">
        <div class="main-content-inner">
            <section class="pdb50">
                <div class="container-fluid">
                    <div class="pdt10 clearfix">
                        <h2 class="page-title mb30">
                            Users
                        </h2>
                    </div>
                    <!-- start main table box -->

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="table-responsive">
                                <table class="table  table-striped  listing-table" id="branch-table">
                                    <thead>
                                    <tr>
                                        <th width="10">identification_number</th>
                                        <th>username</th>
                                        <th>mobile</th>
                                        <th>department</th>
                                        <th>user_roll</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    {% for person in persons %}
                                        <tr>
                                            <th class="sr-no">{{ person.identification_number }}</th>
                                            <td>
                                                {{ person.user.username|default_if_none:'' }}
                                            </td>
                                            <td>
                                                {{ person.mobile|default_if_none:'' }}
                                            </td>
                                            <td>
                                                {{ person.get_department_display }}
                                            </td>
                                            <td>
                                                {{ person.get_user_roll_display }}
                                            </td>

                                            <td class="text-center actions">
                                                {#            <a href="{% url 'iss:setup_update_person' person.id %}" class="editbox animated  fadeIn"><i class="fa fa-pencil"></i></a> &nbsp;#}
                                                {#            <a href="#" class="deletebox animated  fadeIn fadeIn js-delete-branch"#}
                                                {#               data-url=""><i class="fa fa-trash"></i>#}
                                                {#            </a>#}
                                            </td>
                                        </tr>
                                    {% empty %}
                                        <tr>
                                            <td colspan="5" class="text-center  bg-warning fs15">
                                                No data found
                                            </td>
                                        </tr>
                                    {% endfor %}

                                    </tbody>
                                    <tfoot>
                                    </tfoot>
                                </table>
                            </div>
                            <div class="table-pagination-area">
                                <div class="row">
                                    <div class="col-md-7">
                                        <div>
                                            {% if persons.has_other_pages %}
                                                <ul class="pagination">
                                                    {% if persons.number == 1 %}
                                                        <li class="disabled"><span>⇤</span></li>
                                                    {% else %}
                                                        <li><a class="page-link"
                                                               href="?{% url_replace request 'page' 1 %}">⇤</a></li>
                                                    {% endif %}
                                                    {% if persons.has_previous %}
                                                        <li><a class="page-link"
                                                               href="?{% url_replace request 'page' persons.previous_page_number %}">&laquo;</a>
                                                        </li>
                                                    {% else %}
                                                        <li class="disabled"><span>&laquo;</span></li>
                                                    {% endif %}
                                                    {% for i in persons.paginator|proper_paginate:persons.number %}
                                                        {% if persons.number == i %}
                                                            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span>
                                                            </li>
                                                        {% else %}
                                                            <li><a class="page-link"
                                                                   href="?{% url_replace request 'page' i %}">{{ i }}</a>
                                                            </li>
                                                        {% endif %}
                                                    {% endfor %}
                                                    {% if persons.has_next %}
                                                        <li><a class="page-link"
                                                               href="?{% url_replace request 'page' persons.next_page_number %}">&raquo;</a>
                                                        </li>
                                                    {% else %}
                                                        <li class="disabled"><span>&raquo;</span></li>
                                                    {% endif %}
                                                    {% if persons.number == persons.paginator.num_pages %}
                                                        <li class="disabled"><span>⇥</span></li>
                                                    {% else %}
                                                        <li><a class="page-link"
                                                               href="?{% url_replace request 'page' persons.paginator.num_pages %}">⇥</a>
                                                        </li>
                                                    {% endif %}
                                                </ul>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- end main table box -->
                    <!-- start previous and next button -->

                    <!-- Modal start-->
                    <div class="modal fade form-modal" id="modal-form">
                        <div class="modal-dialog">
                            <div class="modal-content">

                            </div>
                        </div>
                    </div>

                </div>
            </section>
        </div>
    </div>
{% endblock %}


{% block javascript %}
    <script>
    </script>
{% endblock %}