course/urls.py
from django.urls import path

app_name = 'course'

urlpatterns = [

]

course_management/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.urls import path, include
from person.views import DashboardView

urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), {'next_page': '/'}, name='logout'),
    path('persons/', include('person.urls', namespace='person')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

person/urls.py
from django.urls import path
from person.views import PersonListView, PersonCreateView, CeleryBulkStudentCreateView

app_name = 'person'

urlpatterns = [
    path('', PersonListView.as_view(), name='person_list'),
    path('create/', PersonCreateView.as_view(), name='create_person'),
    path('bulk_student_create/', CeleryBulkStudentCreateView.as_view(), name='bulk_student_create'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% include '_partial/head.html' %}
</head>

<body>
<!--[if lt IE 8]>
{#        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>#}
<![endif]-->

{#        {% if user|has_group:'provider' %}#}
{#            {% include 'provider_header.html' %}#}
{##}
{#        {% elif user|has_group:'employee' %}#}
{#            {% include 'customer_header.html' %}#}
{##}
{#        {% else %}#}
{#            {% include 'general_header.html' %}#}
{#        {% endif %}#}

{# ======================== Main Content Starts ==================================== #}
{% block content %}
{% endblock content %}
{# ======================== Main Content Ends  ==================================== #}

<!-- // End Footer  -->
{% include '_partial/footer_js.html' %}

{% block javascript %}

{% endblock javascript %}

</body>
</html>

templates/messages.html
<div class="fleet-magesess" style="float:right">
    {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
        </div>
    {% endfor %}
</div>

templates/sidebar.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <div class="outer-wrapper {% if request.resolver_match.url_name != 'dashboard' %} outer-wrapper-dropdown-active {% endif %} ">
        <div class="sidebar  ">
            <div class="sidebar__humbarger" id="sidebar__humbarger">
                <span></span>
                <span></span>
                <span></span>
            </div>

            <div class="sidebar__inner">
                <div class="sidebar-menu">
                    <ul class="nav panel-list menu-accordion">
                        {#                        <li>#}
                        {#                            <a href="{% url 'dashboard' %}" class="branding-top">#}
                        {#                                <span class="menu-text menu-text__overwrite">Project  <img#}
                        {#                                        src="{% static 'images/plus.svg' %}" alt="Plus"></span>#}
                        {#                            </a>#}
                        {##}
                        {#                        </li>#}
                        <li>
                            <a href="{% url 'dashboard' %}"
                               class=" {% if request.resolver_match.url_name == 'dashboard' %} active {% endif %}">
                                <i class="icon-icommon-home sidebar-menu__icon"></i>
                                <span class="menu-text menu-text__overwrite">Dashboard</span>
                            </a>
                        </li>
                        <li>
                            <a href="#"
                               class="{% if request.resolver_match.namespace == 'person' %} active {% endif %} has-submenu">
                                <i class="icon-icommon-iconlist sidebar-menu__icon"></i>
                                <span class="menu-text menu-text__overwrite">Users</span>
                            </a>
                            <div class="dropdown {% if request.resolver_match.namespace == 'person' %}menu-show {% endif %}">
                                <ul>
                                    <li>
                                        <a class="heading active" href="#">
                                            <span class="submenu-text">General Users</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a class="{% if request.resolver_match.url_name == 'person_list' %} active {% endif %}"
                                           href="{% url 'person:person_list' %}">
                                            <span class="submenu-text">User List</span>
                                        </a>
                                    </li>

                                    <li>
                                        <a class="{% if request.resolver_match.url_name == 'create_person' %} active {% endif %}"
                                           href="{% url 'person:create_person' %}">
                                            <span class="submenu-text">Add User</span>
                                        </a>
                                    </li>

                                    <li>
                                        <a class="{% if request.resolver_match.url_name == 'bulk_student_create' %} active {% endif %}"
                                           href="{% url 'person:bulk_student_create' %}">
                                            <span class="submenu-text">Add Bulk Student</span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </li>


                    </ul>
                    <!-- Default dropup button -->
                    <div class="btm-setting dropup">
                        <a href="#" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">
                            <img src="{% static 'images/avater.png' %}" width="40px" class="img-circle">
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="#"> <i class="fa fa-cog" aria-hidden="true"></i> Settings</a>
                            <a class="dropdown-item" href="{% url 'logout' %}"><i class="fa fa-sign-out"
                                                                                  aria-hidden="true"></i>
                                Logout</a>
                        </div>
                    </div>
                </div>
            </div>
            <a href="" class="angle-show">
                <i class="fa fa-angle-double-right"></i>
            </a>
        </div>
        {% include 'messages.html' %}
        {% block main_content %}

        {% endblock %}
    </div>
{% endblock %}